services:

  github-runner-01:
    container_name: github-runner-01
    environment:
      GH_URL: "${GH_URL}"
      GH_TOKEN: "${GH_TOKEN}"
      GH_RUNNER_NAME: "dev-github-runner-01"
      GH_RUNNER_LABEL: "self-hosted-ci,linux,x64"
    build:
      network: host
      context: ./
      dockerfile: ./Dockerfile
